Predict module
pyronear/pyro-risks pull request #25
Opened 2020-12-11 23:18 UTC by miltminz

This PR introduces important new functionalities like:
- `queries_api.py`: Query FWI and ERA5 data from CDS API
- `predict.py`: introduces predict object `PyroRisk` which instantiates with a trained model and returns predictions for an input day
- functions that takes care of the ingestion and transform the data in order to be predicted by the model
- unitary tests

2020-12-11 23:25 UTC, frgfm requested changes
Thanks for the PR! Only a little trailing whitespace, but most importantly: adding cdsapi to requirements :pray:

The rest looks good to me!

2020-12-11 23:25 UTC, frgfm commented on pyro_risks/datasets/queries_api.py
> +    Information on FWI can be found here:
Trailing whitespace here apparently

2020-12-11 23:30 UTC, miltminz commented on pyro_risks/datasets/queries_api.py
> +    Information on FWI can be found here:
yes thanks, it's fixed

2020-12-12 11:28 UTC, chloeskt commented
Thank you for this PR @miltminz, you did an amazing job ! 🤗  All good for me 👍

2020-12-12 11:28 UTC, chloeskt approved these changes

2020-12-12 11:49 UTC, frgfm approved these changes
Thank you for the PR! All good on my side, we only have to keep in mind that we'll need to optimize the tests that are consuming precious free Github workflows minutes :sweat_smile: 

I'll open a PR!

2020-12-12 11:50 UTC, merged