doc: type hinting enforcing
pyronear/pyro-risks pull request #55
Opened 2021-04-19 18:48 UTC by GHCamille

This PR enforces type-hinting, as introduced in issue #39 , ensuring that all functions are correctly typed.

2021-05-02 07:01 UTC, dataJSA commented
Thanks for the PR @GHCamille that's awesome 😃 , it looks good to me there only a few changes to make with respect to the code quality standards! No worry these issues were introduced before you refactored the functions but they fall under the scope of this PR!

2021-05-02 07:20 UTC, dataJSA requested changes

2021-05-02 07:20 UTC, dataJSA commented on pyro_risks/datasets/fwi.py
> +    def __init__(self, days_list: List[str] = ["20190101"]) -> None:
See codacity: 
https://app.codacy.com/gh/pyronear/pyro-risks/file/55703095880/issues/source?bid=20424053&fileBranchId=23145733#l228

```suggestion
    def __init__(self, days_list: Optional[List[str]] = None) -> None:
        day_list = ["20190101"] if day_list is None else day_list
```

2021-05-02 07:20 UTC, dataJSA commented on pyro_risks/pipeline/predict.py
> +    def get_input(self, day: str) -> pd.DataFrame:
```suggestion
    @staticmethod
    def get_input(day: str) -> pd.DataFrame:
```

2021-05-02 07:20 UTC, dataJSA commented on pyro_risks/pipeline/score_v0.py
> +def prepare_dataset(
See:
https://app.codacy.com/gh/pyronear/pyro-risks/file/55703095833/issues/source?bid=20424053&fileBranchId=23145733#l74

```suggestion
import config as cfg

   df: pd.DataFrame, selected_dep: Optional[List[str]] = None
) -> Tuple[pd.DataFrame, pd.Series]:

     selected_dep = cfg.SELECTED_DEP if selected_dep is None else selected_dep
```

2021-05-03 09:03 UTC, GHCamille commented
Thanks, I honestly didn't understand those errors like it's not even stuff I changed so how come it's not valid 😅 Thank youuu

2021-05-03 09:54 UTC, GHCamille commented
Coming back to it later - Apparent problem with GHCN data that doesn't seem related to the PR

2021-05-04 09:13 UTC, dataJSA approved these changes

2021-05-04 11:39 UTC, merged